### ISSUE TITLE
Can not use OpenAI SDK with Sentry Node agent: TypeError: getDefaultAgent is not a function

### ISSUE THREAD

**Issue by keithwhor** [openai/openai-node#1010]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Referenced previously here, closed without resolution: https://github.com/openai/openai-node/issues/903

This is a pretty big issue as it prevents usage of the SDK while using the latest Sentry monitoring package.

### To Reproduce

1. Install Sentry Node sdk via `npm i @sentry/node --save`
2. Enter the following code;

```javascript
import * as Sentry from '@sentry/node';

// Start Sentry
  Sentry.init({
    dsn: "https://your-sentry-url",
    environment: "your-env",
    tracesSampleRate: 1.0, //  Capture 100% of the transactions
  });
  ```
  
  3. Try to create a completion somewhere in the process after Sentry has been initialized:

```javascript
const params = {
  model: model,
  stream: true,
  stream_options: {
    include_usage: true
  },
  messages
};
const completion = await openai.chat.completions.create(params);
```

Results in error:

```
TypeError: getDefaultAgent is not a function
    at OpenAI.buildRequest (file:///my-project/node_modules/openai/core.mjs:208:66)
    at OpenAI.makeRequest (file:///my-project/node_modules/openai/core.mjs:279:44)
```

### Code snippets

(Included)

### OS

All operating systems (macOS, Linux)

### Node version

v20.10.0

### Library version

v4.56.0

**Comment by rattrayalex** [comment]
I definitely agree this is not a good situation. 

It is essentially a Sentry bug, and the [workaround is documented in associated GitHub issue on their package](https://github.com/getsentry/sentry-javascript/issues/12414#issuecomment-2272789736):

> The workaround for this issue for now is to exclude openai from being instrumented via the `registerEsmLoaderHooks` init option:
> 
> import * as Sentry from '@sentry/node';
> 
> Sentry.init({
>   dsn: '__DSN__',
>   registerEsmLoaderHooks: { exclude: [/openai/] },
> })
> If you're using `@sentry/node/preload` you'll need to create your own preload file to pass this option: `preload.mjs`
> 
> import * as Sentry from '@sentry/node';
> 
> Sentry.preloadOpenTelemetry({
>   registerEsmLoaderHooks: { exclude: [/openai/] },
> })
> ```
> node --import ./preload.mjs ./my-app.mjs
> ```

which is [confirmed](https://github.com/getsentry/sentry-javascript/issues/12414#issuecomment-2278299135) by other users to fix the stacktrace reported here.

For more background, both Sentry and Datadog make use of `import-in-the-middle`, which is causing this issue. [According to a contributor to `import-in-the-middle`](https://github.com/nodejs/import-in-the-middle/pull/113#issuecomment-2210778016), this is due to a fundamental flaw in that library.
 
A more general [workaround](https://github.com/openai/openai-node/issues/903#issuecomment-2233507179) was documented in the other thread, but I believe it may need to be implemented at the library level, so I shared details in the associated [Datadog issue](https://github.com/DataDog/dd-trace-js/issues/4277) as well.

Note that I expect this problem to go away in the next major version of this library, when we [switch from `node-fetch` to the built-in `fetch`](https://github.com/openai/openai-node/pull/402) and can remove most of [these shims](https://github.com/openai/openai-node/blob/39731a60b99053d41b1943c85e115c2f23ccb2b9/src/_shims/registry.ts#L27-L65), which pretty fundamentally conflict with [the underlying bug in `import-in-the-middle`](https://github.com/nodejs/import-in-the-middle/issues/38). I'm hoping that happens within a month or so.

**Comment by rattrayalex** [comment]
Actually, I'll keep this issue open until the next major version, as a reminder to double-check that it does indeed resolve this problem.

**Comment by keithwhor** [comment]
Thanks for the quick response! And thanks for leaving this open, issue #903 was the first thing that popped up when googling so I think it'll be helpful for folks to see there's a resolution available from this library. Looking forward to the next version!

**Comment by BlazingTide** [comment]
Is there a way to resolve this problem?

**Comment by keithwhor** [comment]
As per Alex's comment from the Sentry package, this resolved the problem for me;

```javascript
// Start Sentry
  Sentry.init({
    dsn: "https://my-dsn",
    // add this to resolve bug
    registerEsmLoaderHooks: {
      exclude: [/openai/]
    }
  });
```

**Comment by RobertCraigie** [comment]
I believe this should be fixed in v5 but we have not explicitly tested it yet, would anyone be bale to confirm?

**Comment by RobertCraigie** [comment]
Going to go ahead and close this as it should work, please re-open if it doesn't!
