### ISSUE TITLE
Using Structured Outputs throws `body used already for: https://api.openai.com/v1/chat/completions` in 4.59.0

### ISSUE THREAD

**Issue by jreidgreer** [openai/openai-node#1102]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Since `4.59.0`, using structured outputs with Zod causes the following error:

```
TypeError: body used already for: https://api.openai.com/v1/chat/completions
    at Response.consumeBody (/dev/app/node_modules/node-fetch/lib/index.js:344:30)
    at Response.json (/dev/app/node_modules/node-fetch/lib/index.js:269:22)
    at Proxy.defaultParseResponse (/dev/app/node_modules/openai/src/core.ts:68:33)
    at /dev/app/node_modules/openai/src/core.ts:121:42
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /dev/app/dist/apps/api/main.js:4027:32
    at executeWithRetryAndRateLimiting (/dev/app/dist/apps/api/main.js:4357:20)
    at /dev/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /dev/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

### To Reproduce

You can reproduce by using the chat completions endpoint with structured outputs. I haven't tried this without Zod.

```ts
const completion = await this.client.beta.chat.completions.parse(
  {
    model: "gpt-4o-mini-2024-07-18",
    temperature: 0,
    messages: [
      {
        role: "system",
        content: prompt,
      },
      {
        role: "user",
        content: input,
      },
    ],
    response_format: zodResponseFormat(schema, schemaName),
  },
  { timeout: 60_000 },
);
```

Using `this.client.chat.completions.create` with `response_format: { type: "json_object" }` works just fine.

**This is a regression** introduced in `v4.59.0`

### OS

macOS

### Node version

v20.13.1

### Library version

4.59.0

**Comment by jreidgreer** [comment]
Looking at a comparison with `v4.58.2` and `v4.59.0`: https://github.com/openai/openai-node/compare/v4.58.2...v4.59.0

This seems like the most likely candidate: https://github.com/openai/openai-node/pull/1058

**Comment by RobertCraigie** [comment]
Thanks for the report @jreidgreer, I can't reproduce this, could you share more details about how you're using the SDK?

**Comment by rattrayalex** [comment]
@jreidgreer can you share a stackblitz or equivalent that reproduces the bug?

**Comment by RobertCraigie** [comment]
I'm going to go ahead and close this as we couldn't reproduce.

Please re-open this if you're still running into this error!
