### ISSUE TITLE
UnhandledPromiseRejectionWarning originating from OpenAI library

### ISSUE THREAD

**Issue by AaronMeyers** [openai/openai-node#142]
### Describe the bug

I'm using the Langchain library in conjunction with the OpenAI API to create a conversational agent.

Everything is working fine locally, but when I deploy to a render.com server, when I make a request, I get an error that orginates with the OpenAI api. Here is the call stack:

```
Apr 14 04:09:03 PM  (node:94) UnhandledPromiseRejectionWarning: ReferenceError: Headers is not defined
Apr 14 04:09:03 PM      at createRequest (file:///opt/render/project/src/node_modules/langchain/dist/util/axios-fetch-adapter.js:234:21)
Apr 14 04:09:03 PM      at fetchAdapter (file:///opt/render/project/src/node_modules/langchain/dist/util/axios-fetch-adapter.js:164:21)
Apr 14 04:09:03 PM      at dispatchRequest (/opt/render/project/src/node_modules/axios/lib/core/dispatchRequest.js:58:10)
Apr 14 04:09:03 PM      at Axios.request (/opt/render/project/src/node_modules/axios/lib/core/Axios.js:108:15)
Apr 14 04:09:03 PM      at Function.wrap [as request] (/opt/render/project/src/node_modules/axios/lib/helpers/bind.js:9:15)
Apr 14 04:09:03 PM      at /opt/render/project/src/node_modules/openai/dist/common.js:149:22
Apr 14 04:09:03 PM      at /opt/render/project/src/node_modules/openai/dist/api.js:1738:133
Apr 14 04:09:03 PM  (Use `node --trace-warnings ...` to show where the warning was created)
Apr 14 04:09:03 PM  (node:94) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
Apr 14 04:09:03 PM  (node:94) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### To Reproduce

I'm using the ConversationChain class from Langchain that makes a call to the OpenAI api.

I apologize if this is not the appropriate place to report this bug, but the call stack goes back to the OpenAI api, so it seemed like it might be a good place to look for a solution.

### Code snippets

```JavaScript
response = await chain.call({
  userInput: userInput
});
```

### OS

macOS (locally) and render.com when i deploy remotely

### Node version

Node v18.12.1

### Library version

3.2.1

**Comment by AaronMeyers** [comment]
ok... i got around this by bumping the node version up to 18.13. Also tried 19 and that worked too.
