### ISSUE TITLE
A defect occurs when using openai.images.edit

### ISSUE THREAD

**Issue by BigBlackSheep527** [openai/openai-node#201]
### Describe the bug

 e: APIConnectionTimeoutError
      at OpenAI.request (/Users/123456/Desktop/project/api-chat-node/node_modules/openai/core.js:265:49)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async editImage (/Users/123456/Desktop/project/api-chat-node/api/editImage/index.js:57:16)
      at async /Users/123456/Desktop/project/api-chat-node/app.js:22:22 {
    status: undefined,
    headers: undefined,
    error: undefined,
    code: undefined,
    param: undefined,
    type: undefined
  }

### To Reproduce

try{
		const __data=await openai.images.edit({
			image:fs.createReadStream('api/editImage/dog.png') ,
			prompt: "Make it a little HD",
			n: 1,
			size: "256x256",
		});
		console.log(54,{__data})
		return {data:__data.data}
	} catch(e){
		console.log(26,{e})
		return {e}
	}，
	If I use the above code, there will be an error：
	26 {
  e: APIConnectionTimeoutError
      at OpenAI.request (/Users/123456/Desktop/project/api-chat-node/node_modules/openai/core.js:265:49)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async editImage (/Users/123456/Desktop/project/api-chat-node/api/editImage/index.js:57:16)
      at async /Users/123456/Desktop/project/api-chat-node/app.js:22:22 {
    status: undefined,
    headers: undefined,
    error: undefined,
    code: undefined,
    param: undefined,
    type: undefined
  }
}
The basis is that I can't be sure if "image" is certain, "dog.png" is real

### OS

macOS

### Node version

v18.12.1

### Library version

4.0.0-beta.4

**Comment by rattrayalex** [comment]
It looks like you're getting `APIConnectionTimeoutError`. This may be due to network issues. Note also [OpenAI's supported countries list](https://platform.openai.com/docs/supported-countries).

Do other requests, like a basic "hello world" chat completion, succeed?

**Comment by BigBlackSheep527** [comment]
> 看起来你正在得到`APIConnectionTimeoutError`. 这可能是由于网络问题造成的。另请注意[OpenAI 支持的国家/地区列表](https://platform.openai.com/docs/supported-countries)。
> 
> 其他请求（例如基本的“hello world”聊天完成）是否会成功？



> It looks like you're getting `APIConnectionTimeoutError`. This may be due to network issues. Note also [OpenAI's supported countries list](https://platform.openai.com/docs/supported-countries).
> 
> Do other requests, like a basic "hello world" chat completion, succeed?

When I used "openai.image.generate", it was perfectly fine
`
    const openai=new OpenAI({
		apiKey:defaultData.apiKey,
	})
   const data=	await  openai.images.generate({
		prompt:"A Wolf",
		n:1,
		size:"256x256",
		response_format:"b64_json"
	})
`

**Comment by rattrayalex** [comment]
Interesting. What is the size of the file? Does the same request work with `curl`?

**Comment by BigBlackSheep527** [comment]
> Interesting. What is the size of the file? Does the same request work with `curl`?

I fixed that because I did not set "timeOut", I kept thinking that using "openai.images.edit" was a failure. When I set "timeOut" to 60 seconds, after more than 10 seconds, it worked fine. I'm sorry I caused you any doubt. I have one complaint,
"openai.images.edit" gave me no surprises, and its effect made me feel the same as "openai.images.generate".

**Comment by rattrayalex** [comment]
Thanks @BigBlackSheep527 , I'm glad that worked for you.
