### ISSUE TITLE
 No listener for endpoint: /chat/completions

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [openai/openai-node#264]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hi there, I am trying to use openai under a custom proxy that perfectly works in python 

```python

import base64
import os
import openai
openai.api_type = "azure"
openai.api_base = "https://test.capi.foo.com/z/baa/s/openai-proxy/v1/dev"
openai.api_version = "2023-05-15"

client_key = "asddsaads"
client_secret = "asddasdas"

id_secret_bytes = client_key + ':' + client_secret
encoded_u = base64.b64encode(id_secret_bytes.encode()).decode()

openai.api_key = encoded_u
```

This works, if I try to use the same API_KEY and js 

```javascript
import "dotenv/config";

config({ path: ".env.local" });

import OpenAI from "openai";
import { OpenAIStream, StreamingTextResponse } from "ai";
import { config } from "dotenv";

const apiKey = process.env.OPENAI_API_KEY;

const openai = new OpenAI({
  apiKey,
  baseURL: process.env.OPENAI_API_BASE,
  defaultQuery: {
    "api-version": process.env.OPENAI_API_VERSION,
    "api-type": "azure",
    engine: "gpt-35-turbo",
  },
  defaultHeaders: { "api-key": apiKey },
});

// Extract the `messages` from the body of the request
const messages = [
  {
    role: "assistant",
    content: "You are an helpful AI assistant",
  },
  {
    role: "user",
    content: "Hi",
  },
];

// Ask OpenAI for a streaming chat completion given the prompt
const response = await openai.chat.completions.create({
  model: "gpt-35-turbo",
  stream: false,
  messages,
});
console.log(response);
```

Got

```bash
 return new NotFoundError(status, error, message, headers);
             ^

NotFoundError: No listener for endpoint: /chat/completions
    at APIError.generate (file:///Users/FRANCESCO.ZUPPICHINI/Documents/ai-callcenter/node_modules/.pnpm/openai@4.3.1/node_modules/openai/error.mjs:40:14)
    at OpenAI.makeStatusError (file:///Users/FRANCESCO.ZUPPICHINI/Documents/ai-callcenter/node_modules/.pnpm/openai@4.3.1/node_modules/openai/core.mjs:263:21)
    at OpenAI.makeRequest (file:///Users/FRANCESCO.ZUPPICHINI/Documents/ai-callcenter/node_modules/.pnpm/openai@4.3.1/node_modules/openai/core.mjs:303:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/FRANCESCO.ZUPPICHINI/Documents/ai-callcenter/openai_test.mjs:35:18 {
  status: 404,
  headers: {
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'text/plain',
    date: 'Tue, 29 Aug 2023 12:47:04 GMT',
    'set-cookie': 'visid_incap_2400092=KVo4zJAxTxa6rYkESpXuCMjo7WQAAAAAQUIPAAAAAACxdwEKlhJWCX84EuNd5v87; expires=Tue, 27 Aug 2024 22:52:20 GMT; HttpOnly; path=/; Domain=.capi.zurich.com, nlbi_2400092=rS+SYnhz6SBgo0oSGFnVPwAAAADI7QuUEJlvqfawu0B7wAl0; path=/; Domain=.capi.zurich.com, incap_ses_184_2400092=D0pXK1qNkDgXDMPCwLONAsjo7WQAAAAAxqnHEBN3OkZhRmjzZDs+BQ==; path=/; Domain=.capi.zurich.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains;',
    'transfer-encoding': 'chunked',
    'x-cdn': 'Imperva',
    'x-iinfo': '13-133608846-133608863 NNYN CT(48 45 0) RT(1693313224096 39) q(0 0 1 -1) r(1 1) U6'
  },
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}

Node.js v20.3.0
```

Thanks a lot

### To Reproduce

Impossible since you don't have access to our endpoints :(

### OS

maxOS

### Node version

Node v20.3.0

### Library version

latest

**Comment by rattrayalex** [comment]
You're getting a 404 error from your own server (or from Azure), so this is not an SDK bug; you may want to inspect the server logs for more details.

My suspicion is that you need to include more components in the `baseURL`, such as `/deployments/${model}`, like in in our Azure example: https://github.com/openai/openai-node/blob/master/examples/azure.ts#L24

Inspecting the URL your proxy sends to Azure may help.
