### ISSUE TITLE
Im not sure why but I keep getting this error.

### ISSUE THREAD

**Issue by kenhuang1964** [openai/openai-node#270]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I keep getting this error, but I have already consulted the documentation to ensure that my code is correct. I have the most up-to-date version of openai installed through npm. 
![gnome-shell-screenshot-3cpmh8](https://github.com/openai/openai-node/assets/87556616/b4e92727-8897-4174-8526-d7a032dfbe39)

![gnome-shell-screenshot-3biwep](https://github.com/openai/openai-node/assets/87556616/899682e8-4f32-4480-b47e-6542404a9f98)

### To Reproduce

I am using expo react native. The dataURI is the path to the audio recording saved in m4a format. 

### OS

pop os linux

### Node version

Node v18.16.0

### Library version

openai ^4.3.1

**Comment by kenhuang1964** [comment]
Hey @rattrayalex thanks! I switched to node now. However, whenever I make an API call, I get this error:
```
Error: BadRequestError: {"message":"","type":"server_error","param":null,"code":null}
    at APIError.generate (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/error.js:46:14)
    at OpenAI.makeStatusError (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/core.js:312:29)
    at OpenAI.makeRequest (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/core.js:352:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async transcribe (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:23:22)
    at async /mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:38:26 {
  status: 400,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '7ffad3a8eaef17ea-SJC',
    connection: 'keep-alive',
    'content-length': '103',
    'content-type': 'application/json',
    date: 'Fri, 01 Sep 2023 04:39:03 GMT',
    'openai-processing-ms': '67',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-ratelimit-limit-requests': '50',
    'x-ratelimit-remaining-requests': '49',
    'x-ratelimit-reset-requests': '1.2s',
    'x-request-id': '126fd61b368199767f3aec49ff25eef5'
  },
  error: { message: '', type: 'server_error', param: null, code: null },
  code: null,
  param: null,
  type: 'server_error'
}
```

Here is my code for the API call:
```
    const type = await fileType.fromBuffer(audioFile);
    console.log(`Detected file type: ${JSON.stringify(type)}`);

    const response = await openai.audio.transcriptions.create({
        file: audioFile, // The audio file to transcribe.
        model: "whisper-1", // The model to use for transcription.
        response_format: 'json', // The format of the transcription.
        language: 'en' // Language
    });
 ```
 The file type of audioFile is m4a, which is supported when I checked the docs. Can you please help me?

**Comment by rattrayalex** [comment]
Sorry for the poor error message coming from the API there, I'll see if we can get that improved. Can you show me the code used to get the `audioFile`?

**Comment by kenhuang1964** [comment]
Hey @rattrayalex yes, thank you for your help! 
![gnome-shell-screenshot-g3dx1f](https://github.com/openai/openai-node/assets/87556616/757e4548-4f51-4dff-b449-fc699eff924e)

**Comment by kenhuang1964** [comment]
Hey @rattrayalex thank you for your help!

![image](https://github.com/openai/openai-node/assets/87556616/e20d96b2-c346-4549-899a-72fa8ef5dc38)

**Comment by rattrayalex** [comment]
You want the raw bytes, not a data URI, to send to the API.

**Comment by kenhuang1964** [comment]
Hey @rattrayalex, I have tried to make some modifications to send it in raw bytes format, but I am having some trouble. 

This is my modified code for App.js:
```
  const stopRecording = async () => {
    console.log("Stopping Recording...")
    setRecording(undefined);
    await recording.stopAndUnloadAsync();
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
    }); 
    const audioURI = recording.getURI();
    console.log('Recording stopped and stored at', audioURI);

    // Read the audio file as raw bytes
    const audioFile = await FileSystem.readAsStringAsync(audioURI, {
      encoding: FileSystem.EncodingType.Base64,
    });
    
    const formData = new FormData();
    formData.append('audio', audioFile);

    try { 
      const transcribedText = await fetch('http://192.168.1.45:3000/whisper', {
        method: 'POST',
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        body: formData
      });

      console.log("Transcribed Text:", transcribedText);
      textToSpeech(transcribedText);
    } catch (e) {
      console.error('Error:', e);
    }
  };
  ```
  
  This is my modified code for backend.js:
  ```
  app.post("/whisper", upload.any(), async (req, res) => {
    const audioFileBase64 = req.body.audio;

    if (!audioFileBase64) {
        return res.status(400).json({ error: "'audio' key is missing or undefined in the request body." });
    }

    // Convert Base64 to Buffer
    const audioFileBuffer = Buffer.from(audioFileBase64, 'base64');

    try {
        const response = await transcribe(audioFileBuffer);
        res.send({ 
            type: "POST", 
            transcription: response.data.text
        });
    } catch (e) {
        console.error('Error:', e);
        res.status(500).json({ error: "An error occurred while processing the audio." });
    }
});
```
I am still getting this error:
```
Error: BadRequestError: {"message":"","type":"server_error","param":null,"code":null}
    at APIError.generate (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/error.js:46:14)
    at OpenAI.makeStatusError (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/core.js:312:29)
    at OpenAI.makeRequest (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/core.js:352:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async transcribe (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:16:22)
    at async /mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:39:26 {
  status: 400,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '80090448fd021696-SJC',
    connection: 'keep-alive',
    'content-length': '103',
    'content-type': 'application/json',
    date: 'Sat, 02 Sep 2023 21:58:54 GMT',
    'openai-processing-ms': '66',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-ratelimit-limit-requests': '50',
    'x-ratelimit-remaining-requests': '49',
    'x-ratelimit-reset-requests': '1.2s',
    'x-request-id': '787f5c6e192c6e8372f8de1e9d069baf'
  },
  error: { message: '', type: 'server_error', param: null, code: null },
  code: null,
  param: null,
  type: 'server_error'
}
```

**Comment by rattrayalex** [comment]
I'm not sure what your `transcribe` function looks like, but you might try passing the buffer to our `toFile` helper, and passing that to audio.transcriptions.create function.

**Comment by kenhuang1964** [comment]
Hey @rattrayalex, thanks for that suggestion! I have tried it in my transcribe function. Does this look correct?
```

const transcribe = async (audioBuffer) => {
    const response = await openai.audio.transcriptions.create({
        file: toFile(audioBuffer),
        model: "whisper-1",
        response_format: 'json',
        language: 'en'
    });

    console.log(response.data.text);
    return response;
}
```

**Comment by rattrayalex** [comment]
I think you need to `await toFile` and pass a filename with an appropriate extension, but otherwise, yes.

**Comment by kenhuang1964** [comment]
Hey @rattrayalex, thank you for the suggestion. I have tried to implement that to fix the issue, but it still gives me the same error.

This is my updated backend code:
```
const transcribe = async (audioBuffer) => {
    const audioFile = await toFile(audioBuffer);
    const response = await openai.audio.transcriptions.create({
        file: audioFile,
        model: "whisper-1",
        response_format: 'json',
        language: 'en'
    });

    console.log(response.data.text);
    return response;
}

app.post("/whisper", upload.any(), async (req, res) => {
    const audioFileBase64 = req.body.audio;

    if (!audioFileBase64) {
        return res.status(400).json({ error: "'audio' key is missing or undefined in the request body." });
    }

    // Convert Base64 to Buffer
    const audioFileBuffer = Buffer.from(audioFileBase64, 'base64');

    try {
        const response = await transcribe(audioFileBuffer);
        res.send({ 
            type: "POST", 
            transcription: response.data.text
        });
    } catch (e) {
        console.error('Error:', e);
        res.status(500).json({ error: "An error occurred while processing the audio." });
    }
});

app.listen(port, () => {
    console.log(`Server running on port ${port}`);
});
```

The error I am getting is:
```
Error: BadRequestError: Unrecognized file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']
    at APIError.generate (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/error.js:46:14)
    at OpenAI.makeStatusError (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/core.js:312:29)
    at OpenAI.makeRequest (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/node_modules/openai/core.js:352:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async transcribe (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:17:22)
    at async /mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:39:26 {
  status: 400,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8009460c6f052566-SJC',
    connection: 'keep-alive',
    'content-length': '231',
    'content-type': 'application/json',
    date: 'Sat, 02 Sep 2023 22:43:45 GMT',
    'openai-organization': 'user-4rz6tkfx8u0rleswbuk8xrez',
    'openai-processing-ms': '29',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-ratelimit-limit-requests': '50',
    'x-ratelimit-remaining-requests': '49',
    'x-ratelimit-reset-requests': '1.2s',
    'x-request-id': '90f0786d37d44d69d3cb6debbf5dd11a'
  },
  error: {
    message: "Unrecognized file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']",
    type: 'invalid_request_error',
    param: null,
    code: null
  },
  code: null,
  param: null,
  type: 'invalid_request_error'
}
```

**Comment by rattrayalex** [comment]
You missed this:

> and pass a filename with an appropriate extension

e.g., `await toFile(buffer, 'foo. m4a')`

This is demonstrated in the "File uploads" section of the README: https://github.com/openai/openai-node#file-uploads

**Comment by kenhuang1964** [comment]
Hey @rattrayalex, I tried it initially but got an error, which is why I removed it.

If I use it:
```
const transcribe = async (audioBuffer) => {
    const audioFile = await toFile(audioBuffer, 'audioFile.m4a');
    const response = await openai.audio.transcriptions.create({
        file: audioFile,
        model: "whisper-1",
        response_format: 'json',
        language: 'en'
    });

    console.log(response.data.text);
    return response;
}
```

I get this error:
```
Error: TypeError: Cannot read properties of undefined (reading 'text')
    at transcribe (/mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:24:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /mnt/2tbdir/VSCodeProjects/sovarapp/backend/index.js:39:26
```

**Comment by rattrayalex** [comment]
Hi @kenhuang1964, I'm glad we were able to help you send a successful request!

GitHub issues are for reporting bugs and requesting features in the SDK, not for developer support, so I won't be able to assist any further. You might try using TypeScript to help you debug errors like this, as well as asking in community.openai.com or related discord channels for help from here. In this case, you might try `console.log(response)` to see the shape of data returned from the API.

**Comment by kenhuang1964** [comment]
Hi @rattrayalex 

Thank you for your patience and your previous help! I appreciate it! :heart:

**Comment by ZainAli104** [comment]
I solve this problem using this approch and it works for me:
`import fs from "fs";
import OpenAI from "openai";

const openai = new OpenAI();

async function main() {
  const transcription = await openai.audio.transcriptions.create({
    file: fs.createReadStream("audio.mp3"),
    model: "whisper-1",
  });

  console.log(transcription.text);
}
main();
`

Reference:
[https://platform.openai.com/docs/api-reference/audio/createTranscription?lang=node](url)
