### ISSUE TITLE
Cannot access Audio before initalization

### ISSUE THREAD

**Issue by ShravanSunder** [openai/openai-node#360]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I'm getting this error with nextjs `Cannot access 'Audio' before initialization`
i'm only using chat completion.  

The issue seems to be a circular depedency in index.js and audio.js generated by stainless client.  
- Notice how audio.js is importing  `import * as API from "./index.mjs"`This is not correct and causes issues.  
- More info below in code snippet.

```
Uncaught ReferenceError: Cannot access 'Audio' before initialization
    at Module.Audio (audio.mjs:1:54)
    at Module.Audio (index.mjs:1:54)
    at Object.registerExportsForReactRefresh (helpers.js:52:40)
    at registerExportsAndSetupBoundaryForReactRefresh (runtime-base.ts:438:11)
    at runModuleExecutionHooks (runtime-base.ts:382:7)
    at instantiateModule (runtime-base.ts:321:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:422:10)
    at esmImport (runtime-utils.ts:203:18)
    at audio.mjs:1:54
    at [project]/node_modules/.pnpm/openai@4.11.1/node_modules/openai/resources/audio/audio.mjs (ecmascript) (08b5e__pnpm_360590._.js:141833:3)
    at runtime-base.ts:322:21
    at runModuleExecutionHooks (runtime-base.ts:374:5)
    at instantiateModule (runtime-base.ts:321:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:422:10)
    at esmImport (runtime-utils.ts:203:18)
    at index.mjs:1:54
    at [project]/node_modules/.pnpm/openai@4.11.1/node_modules/openai/resources/index.mjs (ecmascript) (08b5e__pnpm_360590._.js:141878:3)
    at runtime-base.ts:322:21
    at runModuleExecutionHooks (runtime-base.ts:374:5)
    at instantiateModule (runtime-base.ts:321:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:422:10)
    at esmImport (runtime-utils.ts:203:18)
    at index.mjs:1:54
    at [project]/node_modules/.pnpm/openai@4.11.1/node_modules/openai/index.mjs (ecmascript) (08b5e__pnpm_360590._.js:142022:3)
    at runtime-base.ts:322:21
    at runModuleExecutionHooks (runtime-base.ts:374:5)
    at instantiateModule (runtime-base.ts:321:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:422:10)
    at esmImport (runtime-utils.ts:203:18)
    at [project]_packages_askluna-core_src_api_64b410._.js:126:168
    at [project]/packages/askluna-core/src/api/getOpenAIClient.ts (ecmascript) ([project]_packages_askluna-core_src_api_64b410._.js:145:3)
    at runtime-base.ts:322:21
    at runModuleExecutionHooks (runtime-base.ts:374:5)
    at instantiateModule (runtime-base.ts:321:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:422:10)
    at esmImport (runtime-utils.ts:203:18)
    at [project]_packages_askluna-core_src_api_64b410._.js:153:144
    at [project]/packages/askluna-core/src/api/OpenAiModelClient.ts (ecmascript) ([project]_packages_askluna-core_src_api_64b410._.js:215:3)
    at runtime-base.ts:322:21
    at runModuleExecutionHooks (runtime-base.ts:374:5)
    at instantiateModule (runtime-base.ts:321:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:422:10)
    at esmImport (runtime-utils.ts:203:18)
    at [project]_packages_askluna-core_src_services_ai-system_AiSystem_ts_638c3c._.js:8:146
    at [project]/packages/askluna-core/src/services/ai-system/AiSystemAbstract.ts (ecmascript) ([project]_packages_askluna-core_src_services_ai-system_AiSystem_ts_638c3c._.js:66:3)
    at runtime-base.ts:322:21
    at runModuleExecutionHooks (runtime-base.ts:374:5)
    at instantiateModule (runtime-base.ts:321:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:422:10)
```

### To Reproduce

- create nextjs  project
- run with --turbo
- use chat completion

### Code snippets

```JavaScript

// File generated from our OpenAPI spec by Stainless.
export { Audio } from "./audio.mjs";
export { Transcriptions } from "./transcriptions.mjs";
export { Translations } from "./translations.mjs";
//# sourceMappingURL=index.mjs.map
```

```
// File generated from our OpenAPI spec by Stainless.
import { APIResource } from 'openai/resource';
import { Transcriptions } from "./transcriptions.mjs";
import { Translations } from "./translations.mjs";
import * as API from "./index.mjs";
export class Audio extends APIResource {
    constructor() {
        super(...arguments);
        this.transcriptions = new Transcriptions(this.client);
        this.translations = new Translations(this.client);
    }
}
(function (Audio) {
    Audio.Transcriptions = API.Transcriptions;
    Audio.Translations = API.Translations;
})(Audio || (Audio = {}));
//# sourceMappingURL=audio.mjs.map
```
```


### OS

macos

### Node version

v20

### Library version

v4

**Comment by ShravanSunder** [comment]
@rattrayalex this is a blocker in a lot of bundlers

**Comment by rattrayalex** [comment]
Thanks for reporting. Can you share a stackblitz that minimally reproduces this error?

**Comment by rattrayalex** [comment]
We believe we have a fix for this that will be released soon.

**Comment by rattrayalex** [comment]
I believe this should have been fixed in https://github.com/openai/openai-node/releases/tag/v4.12.1 or a more recent release; please let us know if the issue persists in the latest version of the package.
