### ISSUE TITLE
TypeError: the promise constructor cannot be invoked directly - Azure OpenAI 

### ISSUE THREAD

**Issue by olefirenko** [openai/openai-node#361]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When using Azure OpenAI I am getting intermittently the error `TypeError: the promise constructor cannot be invoked directly`

```
TypeError: the promise constructor cannot be invoked directly

    See http://goo.gl/MqrFmX

    at check (/var/task/node_modules/bluebird/js/release/promise.js:86:15)
    at new Promise (/var/task/node_modules/bluebird/js/release/promise.js:96:9)
    at new APIPromise (file:///var/task/node_modules/openai/core.mjs:44:9)
    at OpenAI.request (file:///var/task/node_modules/openai/core.mjs:241:16)
    at OpenAI.methodRequest (file:///var/task/node_modules/openai/core.mjs:157:21)
    at OpenAI.post (file:///var/task/node_modules/openai/core.mjs:145:21)
    at Completions.create (file:///var/task/node_modules/openai/resources/chat/completions.mjs:6:21)
```

### To Reproduce

```
const AZURE_OPENAI_API_INSTANCE_NAME = '';
const AZURE_OPENAI_API_KEY = '';
const AZURE_OPENAI_API_VERSION = '2023-07-01-preview';
const AZURE_OPENAI_API_DEPLOYMENT_NAME = '';

const configAzure = {
          apiKey: AZURE_OPENAI_API_KEY,
          baseURL: `https://${AZURE_OPENAI_API_INSTANCE_NAME}.openai.azure.com/openai/deployments/${AZURE_OPENAI_API_DEPLOYMENT_NAME}`,
          defaultQuery: { 'api-version': AZURE_OPENAI_API_VERSION },
          defaultHeaders: { 'api-key': AZURE_OPENAI_API_KEY },
        };
  
const openai = new OpenAI(configAzure);

const response = await openai.chat.completions.create(
        {
        model: 'gpt-3.5-turbo',
        messages: [
               { role: 'user' , content: 'Write about AI' },
         ],
        n: 3
        top_p: 1,
      frequency_penalty: 0,
      presence_penalty: 0,
        }
      );
```

### OS

Vercel (Linux)

### Node version

18.x

### Library version

4.11.1

**Comment by rattrayalex** [comment]
Interesting. This library subclasses `Promise`, which Bluebird apparently [doesn't allow](http://bluebirdjs.com/docs/error-explanations.html#2.-you-are-trying-to-subclass-promise). 

May I ask why you're using Bluebird in your project, and whether you'd be able to remove it?

**Comment by olefirenko** [comment]
@rattrayalex Thank you so much for your reply!
I had two packages that use Bluebird: 
- `"node-telegram-bot-api": "^0.59.0"`
- `"phantomjscloud": "^3.5.5"`

I replaced them. There is only one package left that has Bluebird as a dependency - `mammoth`. So far no issues, I am observing now. Thank you!

**Comment by rattrayalex** [comment]
Great!
