### ISSUE TITLE
Error thrown when using node's fetch after version 4.12.2

### ISSUE THREAD

**Issue by thhermansen** [openai/openai-node#384]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

See two commits in https://github.com/thhermansen/openai-node-fetch/commits/main

which in essence consists of a rather small program:

```ts
import OpenAI from 'openai'


async function main() {
  new OpenAI({ apiKey: 'SECRET', });

  const response = await fetch('https://google.com')
  console.log(`${response.status} ${response.statusText}`)
}

if (require.main === module) main();
```

It works fine with openai 4.12.1, but breaks in 4.12.2 where you get an error thrown:

```
openai-test/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5
    throw new TypeError(`${context} is not a ReadableStream.`);
          ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (openai-test/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/src/lib/validators/readable-stream.ts:5:11)
    at convertReadableWritablePair (openai-test/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/src/lib/validators/readable-writable-pair.ts:15:3)
    at ReadableStream.ReadableStream.pipeThrough (openai-test/node_modules/.pnpm/web-streams-polyfill@3.2.1/node_modules/web-streams-polyfill/src/lib/readable-stream.ts:211:23)
    at fetchFinale (node:internal/deps/undici/undici:9584:56)
    at mainFetch (node:internal/deps/undici/undici:9476:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The issue is maybe related to 71984edc3141ba99ffa1327bab6a182b4452209f

### To Reproduce

Clone https://github.com/thhermansen/openai-node-fetch and run the code :)

### OS

MacOS

### Node version

20.8.1

### Library version

4.12.1, 4.12.2, 4.12.3

**Comment by rattrayalex** [comment]
Thanks for reporting this, especially with a repro repo. We're looking into it. 

In the meantime, as a workaround, you might try `import 'openai/shims/web'` or `import 'openai/shims/node'` before your first `import 'openai'`.

**Comment by benbalter** [comment]
I ran into the same issue. Downgrading to `4.12.1` solved the problem (the shim imports did not, but I may have done them wrong).

**Comment by rattrayalex** [comment]
Thank you for confirming @benbalter and attempting the workaround! I've identified the issue and have a fix in flight.

**Comment by rattrayalex** [comment]
This will be released in https://github.com/openai/openai-node/pull/386 !
