### ISSUE TITLE
runFunction throws "'content' is a required property - 'messages.1'" error when using Azure openAI integration

### ISSUE THREAD

**Issue by darkneo14** [openai/openai-node#540]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When you use runFunctions function with Azure open AI, it throws the "'content' is a required property - 'messages.1'" error with 400 error code. 

`const runner = openai.beta.chat.completions
    .runFunctions({
          messages: [
            {
              role: "user",
              content: `what is sqauare root of 4?`
            }
          ],
          functions: [
            {
              "name": "calculateSquareRoot",
              "function": calculateSquareRoot,
              "description": "Calculate sqaure root of a number",
              "parameters": { 
                type: 'object', properties: 
                {
                  number: { type: 'integer' },
                } 
              },
            }, 
            {
              "name": "calculateLogBase2",
              "function": calculateLogBase2,
              description: "Calculate log base 2 of a number",
              parameters: { 
                type: 'object', 
                properties: {
                    number: { type: 'integer' },
                } 
              },
            }
          ]
        })`
        
  After debugging in the library, I found the issue. The second gpt call that happens after the function call is missing the content field in the messages object - 
  
  `{
  model: 'gpt-3.5-turbo',
  messages: [
    { role: 'user', content: 'what is sqauare root of 4?' },
    { role: 'assistant', function_call: [Object] },
    { role: 'function', name: 'calculateSquareRoot', content: '2' }
  ],
  functions: [
    {
      name: 'calculateSquareRoot',
      parameters: [Object],
      description: 'Calculate sqaure root of a number'
    },
    {
      name: 'calculateLogBase2',
      parameters: [Object],
      description: 'Calculate log base 2 of a number'
    }
  ],
  function_call: 'auto'
}`    

Here you can see that messages[1].content is not present. In case of openAI call, this is null where it runs smoothly. 
A simple solve is to add - `params.messages = params.messages.map((message) => { message.content = message.content || null; return message; })`.

### To Reproduce

Code to reproduce - 

use azure configuration for openAI initialisation.

`const runner = openai.beta.chat.completions
    .runFunctions({
          model: "gpt-3.5-turbo",
          messages: [
            {
              role: "user",
              content: `what is sqauare root of 4?`
            }
          ],
          functions: [
            {
              "name": "calculateSquareRoot",
              "function": calculateSquareRoot,
              "description": "Calculate sqaure root of a number",
              "parameters": { 
                type: 'object', properties: 
                {
                  number: { type: 'integer' },
                } 
              },
            }, 
            {
              "name": "calculateLogBase2",
              "function": calculateLogBase2,
              description: "Calculate log base 2 of a number",
              parameters: { 
                type: 'object', 
                properties: {
                    number: { type: 'integer' },
                } 
              },
            }
          ]
        })
        console.log(runner)
        const finalContent = await runner.finalContent();`

### OS

macOs

### Node version

node v16.14.2

### Library version

^4.0.0

**Comment by rattrayalex** [comment]
Thanks for reporting! Can you share the traceback / error message you get?

**Comment by darkneo14** [comment]
error stack - 
`/node_modules/openai/error.js:43
            return new BadRequestError(status, error, message, headers);
                   ^

BadRequestError: 400 'content' is a required property - 'messages.1'
    at APIError.generate (/Users/prashant.gupta/Desktop/Ixigo/ixigo-bot-new/node_modules/openai/error.js:43:20)
    at OpenAI.makeStatusError (/Users/prashant.gupta/Desktop/Ixigo/ixigo-bot-new/node_modules/openai/core.js:251:33)
    at OpenAI.makeRequest (/Users/prashant.gupta/Desktop/Ixigo/ixigo-bot-new/node_modules/openai/core.js:290:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatCompletionRunner._createChatCompletion (/Users/prashant.gupta/Desktop/Ixigo/ixigo-bot-new/node_modules/openai/lib/AbstractChatCompletionRunner.js:305:32)
    at async ChatCompletionRunner._runFunctions (/Users/prashant.gupta/Desktop/Ixigo/ixigo-bot-new/node_modules/openai/lib/AbstractChatCompletionRunner.js:333:36)`

**Comment by rattrayalex** [comment]
Thanks! Could you share the code that integrates with this, including where you define the messages you send?

**Comment by darkneo14** [comment]
Sure... Here is the function I am testing this with - 

```
async function testFunctionAzure() {
  const openai = new OpenAI({
    'apiKey': apiKey,
    baseURL: `https://oai.hconeai.com/openai/deployments/${model}`,
    defaultHeaders: {
      "Helicone-OpenAI-API-Base": `https://${resource}.openai.azure.com`,
      'api-key': `${apiKey}`,
    },
    defaultQuery: { "api-version": `${apiVersion}` },
  });

    const runner = openai.beta.chat.completions
    .runFunctions({
          messages: [
            {
              role: "user",
              content: `what is sqauare root of 4?`
            }
          ],
          functions: [
            {
              "name": "calculateSquareRoot",
              "function": calculateSquareRoot,
              "description": "Calculate sqaure root of a number",
              "parameters": { 
                type: 'object', properties: 
                {
                  number: { type: 'integer' },
                } 
              },
            }, 
            {
              "name": "calculateLogBase2",
              "function": calculateLogBase2,
              description: "Calculate log base 2 of a number",
              parameters: { 
                type: 'object', 
                properties: {
                    number: { type: 'integer' },
                } 
              },
            }
          ]
        })
        console.log(runner)
        const finalContent = await runner.finalContent();
        console.log(finalContent)

        function calculateSquareRoot(params) {
            params = JSON.parse(params)
            console.log(params)
            let response = Math.sqrt(params.number);
            console.log("Response ------",response)
            return response
        }

        function calculateLogBase2(params) {
            return Math.log2(params.number);
        }
}
```

**Comment by rattrayalex** [comment]
The fix for this will be released in v4.20.2, and should also be fixed in the next Azure OpenAI API version (cc @johanste).
