### ISSUE TITLE
Connection error -- cause: TypeError: Bearer { "apiKey": "...", "organization": "..." } is not a legal HTTP header value

### ISSUE THREAD

**Issue by windymelt** [openai/openai-node#550]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When I call OpenAI with this library with organization id, it throws Connection error.

```
APIConnectionError: Connection error.     at OpenAI.makeRequest (/workspace/node_modules/.pnpm/openai@4.20.1/node_modules/openai/core.js:279:19)
...
cause: TypeError: Bearer {
  "apiKey": "...",
  "organization": "..."
} is not a legal HTTP header value
at validateValue (/workspace/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:684:9)
at Headers.append (/workspace/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:836:3) 
at new Headers (/workspace/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:761:11) 
at new Request (/workspace/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1231:19) 
at /workspace/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1449:19 
at new Promise (<anonymous>) 
at fetch (/workspace/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1447:9) 
at OpenAI.fetchWithTimeout (/workspace/node_modules/.pnpm/openai@4.20.1/node_modules/openai/core.js:333:20) 
at OpenAI.makeRequest (/workspace/node_modules/.pnpm/openai@4.20.1/node_modules/openai/core.js:268:37) 
} 
```

### To Reproduce

1. Instantiate `OpenAI` with `apiKey` and `organization`
2. Call arbitrary API
3. Connection error occurs 

### Code snippets

```JavaScript
import * as ff from '@google-cloud/functions-framework';
import fs from 'fs';
import OpenAI from 'openai';

ff.http('FooFunction', async (req: ff.Request, res: ff.Response) => {
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY, organization: 'org-foobar' });
  const result = await openai.audio.transcriptions.create({
    file: fs.createReadStream('/tmp/audio.mp4'),
    model: 'whisper-1'
  }).catch(console.error)
});
```

### OS

Linux

### Node version

Node v20 (Google Cloud function runtime)

### Library version

v4.20.1

**Comment by windymelt** [comment]
Sorry, my mistake. Envvar is broken.
