### ISSUE TITLE
on('error', () => ...) event does not fire on "OpenAIError: stream ended without producing a ChatCompletionMessage with role=assistant"

### ISSUE THREAD

**Issue by danny-avila** [openai/openai-node#553]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Similar to #526 except there's no real way to handle this except within `process.on('uncaughtException', (err) => {})`, a hacky workaround I fenagled, or using the old API vs. `openai.beta`.

I understand that this may be exclusive to reverse proxies or other such APIs mimicking OpenAI spec, but perhaps missing a critical spec, but the error should still land where expected to be caught.

> OpenAIError: stream ended without producing a ChatCompletionMessage with role=assistant
    at ChatCompletionStream._AbstractChatCompletionRunner_getFinalMessage (/app/node_modules/openai/lib/AbstractChatCompletionRunner.js:464:11)
    at ChatCompletionStream._AbstractChatCompletionRunner_getFinalContent (/app/node_modules/openai/lib/AbstractChatCompletionRunner.js:455:134)
    at ChatCompletionStream._emitFinal (/app/node_modules/openai/lib/AbstractChatCompletionRunner.js:282:152)
    at /app/node_modules/openai/lib/AbstractChatCompletionRunner.js:77:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### To Reproduce

- Use a reverse proxy service, using an alternate baseURL
    - here is a real scenario reported by a user of my app: https://github.com/danny-avila/LibreChat/issues/1270
    - I was able to reproduce by using [ollama ](https://github.com/jmorganca/ollama) in conjunction with [litellm](https://github.com/BerriAI/litellm)
 - Streaming works and I can add breakpoints to chunks and are indeed partials
 - Error after `finalMessage` listener, is uncaught and will crash node server unless prevented as shown
    - I noticed the `emit: end` is expecting the last message of stream.messages to be an assistant message, so my hack prevents the issue

### Code snippets

```JavaScript
// Here's how I'm handling streams
try {
  const stream = await openai.beta.chat.completions
    .stream({
      ...modelOptions,
      stream: true,
    })
    .on('error', (err) => {
      /* Expect error here */
    })
    .on('finalMessage', (message) => {
      /* role === 'user' here */
    });
  
  for await (const chunk of stream) {
    const token = chunk.choices[0]?.delta?.content || '';
  }
} catch (err) {
  /* If not above, expect error here */
}

// My hacky workaround

try {
  let UnexpectedRoleError = false;
  let intermediateReply = '';
  const stream = await openai.beta.chat.completions
    .stream({
      ...modelOptions,
      stream: true,
    })
    .on('finalMessage', (message) => {
      if (message?.role !== 'assistant') {
        stream.messages.push({ role: 'assistant', content: intermediateReply });
      }
    });
  
  for await (const chunk of stream) {
    const token = chunk.choices[0]?.delta?.content || '';
    intermediateReply += token;
  }
} catch (err) {
//
}
```

### OS

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### Node version

v18.13.0

### Library version

openai v4.20.1

**Comment by Sun-ZhenXing** [comment]
I got this issue with some third-party models, and it's causing Node.js to crash.

```ts
const options: OpenAI.ChatCompletionCreateParams = {
  model,
  temperature,
  top_p,
  stream: true,
  stream_options: {
    include_usage: true,
  },
  messages,
}
const api = openai.beta.chat.completions.stream(options, {
  signal: abortSignal,
})
const response = await api.finalChatCompletion()
```

log:

```console
2024-07-31T01:47:52.530062586Z file:///app/node_modules/.pnpm/openai@4.53.2/node_modules/openai/lib/AbstractChatCompletionRunner.mjs:471
2024-07-31T01:47:52.530086476Z     throw new OpenAIError('stream ended without producing a ChatCompletionMessage with role=assistant');
2024-07-31T01:47:52.530090714Z           ^
2024-07-31T01:47:52.530093988Z
2024-07-31T01:47:52.530097552Z OpenAIError: stream ended without producing a ChatCompletionMessage with role=assistant
2024-07-31T01:47:52.530101219Z     at ChatCompletionStream._AbstractChatCompletionRunner_getFinalMessage (file:///app/node_modules/.pnpm/openai@4.53.2/node_modules/openai/lib/AbstractChatCompletionRunner.mjs:471:11)
2024-07-31T01:47:52.530104880Z     at ChatCompletionStream._emitFinal (file:///app/node_modules/.pnpm/openai@4.53.2/node_modules/openai/lib/AbstractChatCompletionRunner.mjs:279:152)
2024-07-31T01:47:52.530108955Z     at file:///app/node_modules/.pnpm/openai@4.53.2/node_modules/openai/lib/AbstractChatCompletionRunner.mjs:74:22
2024-07-31T01:47:52.530112489Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm sure this problem exists in the latest version as well.

**Comment by HAYDEN-OAI** [comment]
thanks for the detailed report. this fix will be available in the next release.

we updated the shared stream runner so exceptions raised while emitting final events are caught by the same error path as request and parsing failures. if an OpenAI-compatible stream ends without an assistant message, `.on('error', ...)` now receives the `OpenAIError`, and `done()` rejects with that same error instead of leaving an unhandled rejection behind.

we also added a regression test with a malformed stream that produces only a user message, so this behavior stays covered. appreciate the repro!
