### ISSUE TITLE
How to stop streaming

### ISSUE THREAD

**Issue by Dangtrungphu** [openai/openai-node#682]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I use stream.abort(); to stop receive from api , but i have exception below
```
/usr/src/main-api/node_modules/openai/src/lib/ChatCompletionStream.ts:111
      throw new APIUserAbortError();
            ^
Error: Request was aborted.
    at ChatCompletionStream._createChatCompletion (/usr/src/main-api/node_modules/openai/src/lib/ChatCompletionStream.ts:111:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ChatCompletionStream._runChatCompletion (/usr/src/main-api/node_modules/openai/src/lib/AbstractChatCompletionRunner.ts:448:12)
```
I have been follow to guide in the document
> If you need to cancel a stream, you can break from a for await loop or call `stream.abort()`.

### To Reproduce

```Typescript
   const stream = this.openapi.beta.chat.completions.stream({
          messages: input_send,
          model: model_openai,
          stream: true,
          temperature: option.temperature ?? 0.7,
        });

        stream.on('content', async (delta, snapshot) => {
          console.log(delta);
          observer.next({
            data: {
              content: delta,
            }
          });
        });
        stream.on('finalMessage', (message: ChatCompletionMessage) => {
          observer.next({
            data: {
              newMessage: new MessageOpenAiModel().fromJSON({
                content: message.content,
              }),
            }
          });

        });

        stream.on('error', async (error) => {
          observer.next({
            data: {
              newMessage: new MessageOpenAiModel().fromJSON({
                content: error.message,
              }),
            }
          });
        });
        stream.finalChatCompletion().then((chatCompletion) => {
          observer.complete()
        });

        // Lắng nghe sự kiện close từ client
        response.on('close', () => {
          console.log(stream.controller.signal?.aborted);
          observer.complete();
          stream.abort()
        }); 
```

Nope

### OS

Ubuntu

### Node version

16.15.1

### Library version

v4.28.0

**Comment by rattrayalex** [comment]
This is working as intended – you need to add a `.catch` here:

```ts
stream.finalChatCompletion().then((chatCompletion) => {
  observer.complete()
}).catch(err => {
  console.warn(…)
  observer.complete()
})
```

**Comment by Dangtrungphu** [comment]
I have been add `.catch` but, it's still error well as above. 
I want to strop streaming when it not yet final

```Typescript
  response.on('close', () => { 
    console.log(stream.controller.signal?.aborted);
    observer.complete();
    stream.abort() // stop here
  }); 
```

**Comment by Dangtrungphu** [comment]
Can you give me example about stop streaming when OpenAi api is streaming data, and you stop stream before the stream final.

**Comment by rattrayalex** [comment]
Your example looks correct, but I might be missing something. Where does the error get raised?

**Comment by Dangtrungphu** [comment]
I am using SSE to get data from the client, when I disconnect from the client the server receives the `response.on('close')` event to end the stream. 
If I don't do anything, the OpenAi api will still stream data and cause a `memory leak`, so I use `stream.abort()` to completely stop the stream from OpenAi. But I get the above error

My code:
```Typescript
async subscribeconversation(option, response: Response): Promise<Observable<any>> {
  let model_openai = this.getModel(option.version)
  return new Observable<MessageEvent>((observer) => {
    try {
      const stream = this.openapi.beta.chat.completions.stream({
        messages: input_send,
        model: model_openai,
        stream: true,
        temperature: option.temperature ?? 0.7,
      });

      stream.on('content', async (delta, snapshot) => {
        observer.next({
          data: {
            content: delta,
          }
        });
      });
      
      [...]

      stream.finalChatCompletion().then((chatCompletion) => {
        observer.complete()
      }).catch(err => {
        console.log(err)
        observer.complete()
      })

      // Listen event close from client
      response.on('close', async () => {
        observer.complete();
      });

      return async () => {
        stream.abort() // stop stream here
      };
    } catch (error) {
      console.log('log error');
      console.log(error);
      throw error
    }
  });
}
```

**Comment by rattrayalex** [comment]
> But I get the above error

Can you please paste the entire traceback of the error with the new version of the code you just shared?

**Comment by Dangtrungphu** [comment]
This is the error i got:

```
/usr/src/main-api/node_modules/openai/src/lib/ChatCompletionStream.ts:111
      throw new APIUserAbortError();
            ^
Error: Request was aborted.
    at ChatCompletionStream._createChatCompletion (/usr/src/main-api/node_modules/openai/src/lib/ChatCompletionStream.ts:111:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ChatCompletionStream._runChatCompletion (/usr/src/main-api/node_modules/openai/src/lib/AbstractChatCompletionRunner.ts:448:12)
```

**Comment by rattrayalex** [comment]
Nothing else is printed at all?

**Comment by Dangtrungphu** [comment]
That's right, I followed your instructions before, but it still exception this error
```
stream.finalChatCompletion().then((chatCompletion) => {
  observer.complete()
}).catch(err => {
  console.log(err)
  observer.complete()
})
``

**Comment by rattrayalex** [comment]
if you comment out `console.log(err)` does it go away?

**Comment by Dangtrungphu** [comment]
It's really gone, thank you for assisting me

**Comment by rattrayalex** [comment]
Terrific!
