### ISSUE TITLE
TypeError: API.Completions is not a constructor

### ISSUE THREAD

**Issue by NatoBoram** [openai/openai-node#897]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Calling `new OpenAI()` fails when Sentry is preloaded.

```sh
❯ node --import @sentry/node/preload ./dist/index.js
TypeError: API.Completions is not a constructor
    at new OpenAI (file:///home/nato/Code/github.com/NatoBoram/bug-report-sentry/node_modules/.pnpm/openai@4.51.0/node_modules/openai/index.mjs:46:28)
    at file:///home/nato/Code/github.com/NatoBoram/bug-report-sentry/dist/openai.js:3:23
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:109:5)
(node:394397) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

* Bug report at Sentry: https://github.com/getsentry/sentry-javascript/issues/12414
* Minimal reproduction project: https://github.com/NatoBoram/bug-report-sentry/pull/9

### To Reproduce

1. [Set Up Profiling](https://docs.sentry.io/platforms/javascript/guides/gcp-functions/profiling/) with Sentry
2. Use [Late Initialization with ESM](https://docs.sentry.io/platforms/javascript/guides/node/install/late-initializtion/#late-initialization-with-esm)
3. Call `new OpenAI()`

### Code snippets

This is the code that fails:

```ts
import OpenAI from "openai"
const openai = new OpenAI()
```

It fails when the project is started with `node --import @sentry/node/preload`.

### OS

Pop!_OS 22.04 LTS x86_64

### Node version

v22.3.0

### Library version

^4.51.0

**Comment by NatoBoram** [comment]
Confirmed as fixed in Sentry v8.13.0
