### ISSUE TITLE
Edit request giving 404

### ISSUE THREAD

**Issue by zfoster** [openai/openai-node#9]
Hi openai,

I'm currently using completion API and am attempting to use the edit API now as well.

Code:

```
const result = await openAI.createCompletion('text-davinci-002', {
    prompt: `${content}\n\nTl;dr`,
    temperature: 0.7,
    max_tokens: 60,
    top_p: 1.0,
    frequency_penalty: 0.0,
    presence_penalty: 0.0,
  })

const result = await openAI.createEdit('text-davinci-002', {
    input: content,
    instruction: 'Rewrite this more simply',
  })
```

The first request has been working for months and still is, but the second returns this

```
(node:5013) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/zfoster/gravity/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/zfoster/gravity/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/zfoster/gravity/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Let me know if I need to make any changes and if there's an existing example for doing something like a "simplification rewrite". Basically trying to summarize and rewrite the text in more simple words with these two operations.

Thanks!

**Comment by dev-dude** [comment]
URL needs to look like:  "https://api.openai.com/v1/engines/text-davinci-edit-001/edits".

Change model engine from "text-davinci-002" to "text-davinci-edit-001" for edit

**Comment by zfoster** [comment]
I copied from the API reference which has the incorrect engine then? -
https://beta.openai.com/docs/api-reference/edits/create

**Comment by dev-dude** [comment]
Yes, the api docs probably need to be updated. They come out with new models regularly I’m sure.
