### ISSUE TITLE
thread_id not recognized from Thread object

### ISSUE THREAD

**Issue by SpuriousGer** [openai/openai-node#921]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I have the following code:

`const run = await openai.beta.threads.createAndRunPoll({
      thread: thread,
      assistant_id: usedAssistant.id,
});`

Typescript shows no error as it seems to be expecting a Thread object which thread is:
```
    const thread = await openai.beta.threads.create({
      messages: [
        {
          role: 'user',
          content: invoiceExpensePrompt(),
          attachments: [{ file_id: uploadedFile.id, tools: [{ type: 'file_search' }] }],
        },
      ],
    });
```

The error I receive is the following:
```
Failed to generate content from PDF document BadRequestError: 400 Unknown parameter: 'thread.id'.
    at APIError.generate (/app/node_modules/openai/error.js:45:20)
    at OpenAI.makeStatusError (/app/node_modules/openai/core.js:275:33)
    at OpenAI.makeRequest (/app/node_modules/openai/core.js:318:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Threads.createAndRunPoll (/app/node_modules/openai/resources/beta/threads/threads.js:91:21)
    at async getDataFromExpenseInvoicePdf (/app/dist/services/openai.service.js:77:21)
    at async analyzePdfDocumentByOpenAiGpt (/app/dist/controllers/paperless.controller.js:80:12)
    at async postConsumption (/app/dist/controllers/paperless.controller.js:52:30) {
  status: 400,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '89f790f50f719280-FRA',
    connection: 'keep-alive',
    'content-length': '165',
    'content-type': 'application/json',
    date: 'Sun, 07 Jul 2024 11:41:35 GMT',
    'openai-organization': 'jp-abig-gmbh',
    'openai-processing-ms': '9',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=Ny2gnklaMhvob6uOe2uv2ChV7Z4QVp1rTVUR4NH0SQo-1720352495-1.0.1.1-QT.sZQTLPKF6XIBGaGawGdp0JPodPJXgKJYljslhhE.dhJJPth5.n83zNI9pXEezJKBpWv0U4VrcBg.g9PHmgw; path=/; expires=Sun, 07-Jul-24 12:11:35 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=KJyygLXSIziDZQlDRsYxkvnLOu4qJ.w.vFH2Tc.CFvc-1720352495034-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-request-id': 'req_47110214306012817ebd2b3c4e77bd29'
  },
  request_id: 'req_47110214306012817ebd2b3c4e77bd29',
  error: {
    message: "Unknown parameter: 'thread.id'.",
    type: 'invalid_request_error',
    param: 'thread.id',
    code: 'unknown_parameter'
  },
  code: 'unknown_parameter',
  param: 'thread.id',
  type: 'invalid_request_error'
}
```

### To Reproduce

NodeJS Library: Create a function that creates an assistant and a thread, pass it on to the SDK to run and poll.

### OS

Docker

### Node version

Node v22

### Library version

"openai": "^4.52.3"

**Comment by SpuriousGer** [comment]
This is a bit annoying as you cannot use Typescript with the library at the moment. Or am I missing something?

**Comment by RobertCraigie** [comment]
Can you share a full example? the stack trace you shared doesn't align with the snippet

**Comment by SpuriousGer** [comment]
Sorry, here is the full code:

```
export async function getDataFromExpenseInvoicePdf(doc: File) {
  try {
    const usedAssistant = await getOrCreateInvoiceAssistant();
    console.log('usedAssistant', usedAssistant);
    console.log('OPENAI_GPT_ASSISTANT', OPENAI_GPT_ASSISTANT);

    const uploadedFile = await uploadFile(doc);
    console.log('uploadedFile', uploadedFile);

    const thread = await openai.beta.threads.create({
      messages: [
        {
          role: 'user',
          content: invoiceExpensePrompt(),
          attachments: [{ file_id: uploadedFile.id, tools: [{ type: 'file_search' }] }],
        },
      ],
    });
    console.log('thread', thread);

    const run = await openai.beta.threads.createAndRunPoll({
      thread: thread,
      assistant_id: usedAssistant.id,
    });
    console.log('run', run);

    if (run.status === 'completed') {
      const messages = await openai.beta.threads.messages.list(thread.id);
      console.log('messages', messages);
      for (const message of messages.getPaginatedItems()) {
        console.log('message', message);
        console.log('jsonMessage', returnJsonFromMessage(message));
      }
      await openai.files.del(uploadedFile.id);

      return messages;
    }
  } catch (error) {
    console.error('Failed to generate content from PDF document', error);
    throw error;
  }
}
```

The expected body payload for the function is:
`body: OpenAI.Beta.Threads.ThreadCreateAndRunParamsNonStreaming`

Thread is optional, but if it is used, it's the following type:
`ThreadCreateAndRunParamsBase. thread?: OpenAI.Beta.Threads.ThreadCreateAndRunParams.Thread | undefined`

Now, the library has this implementation:
```
  async createAndRunPoll(
    body: ThreadCreateAndRunParamsNonStreaming,
    options?: Core.RequestOptions & { pollIntervalMs?: number },
  ): Promise<Threads.Run> {
    const run = await this.createAndRun(body, options);
    return await this.runs.poll(run.thread_id, run.id, options);
  }
```

The Interface which extends is:
```
export interface ThreadCreateAndRunParamsBase {
  /**
   * The ID of the
   * [assistant](https://platform.openai.com/docs/api-reference/assistants) to use to
   * execute this run.
   */
  assistant_id: string;

  /**
   * Override the default system message of the assistant. This is useful for
   * modifying the behavior on a per-run basis.
   */
  instructions?: string | null;

  /**
   * The maximum number of completion tokens that may be used over the course of the
   * run. The run will make a best effort to use only the number of completion tokens
   * specified, across multiple turns of the run. If the run exceeds the number of
   * completion tokens specified, the run will end with status `incomplete`. See
   * `incomplete_details` for more info.
   */
  max_completion_tokens?: number | null;

  /**
   * The maximum number of prompt tokens that may be used over the course of the run.
   * The run will make a best effort to use only the number of prompt tokens
   * specified, across multiple turns of the run. If the run exceeds the number of
   * prompt tokens specified, the run will end with status `incomplete`. See
   * `incomplete_details` for more info.
   */
  max_prompt_tokens?: number | null;

  /**
   * Set of 16 key-value pairs that can be attached to an object. This can be useful
   * for storing additional information about the object in a structured format. Keys
   * can be a maximum of 64 characters long and values can be a maxium of 512
   * characters long.
   */
  metadata?: unknown | null;

  /**
   * The ID of the [Model](https://platform.openai.com/docs/api-reference/models) to
   * be used to execute this run. If a value is provided here, it will override the
   * model associated with the assistant. If not, the model associated with the
   * assistant will be used.
   */
  model?:
    | (string & {})
    | 'gpt-4o'
    | 'gpt-4o-2024-05-13'
    | 'gpt-4-turbo'
    | 'gpt-4-turbo-2024-04-09'
    | 'gpt-4-0125-preview'
    | 'gpt-4-turbo-preview'
    | 'gpt-4-1106-preview'
    | 'gpt-4-vision-preview'
    | 'gpt-4'
    | 'gpt-4-0314'
    | 'gpt-4-0613'
    | 'gpt-4-32k'
    | 'gpt-4-32k-0314'
    | 'gpt-4-32k-0613'
    | 'gpt-3.5-turbo'
    | 'gpt-3.5-turbo-16k'
    | 'gpt-3.5-turbo-0613'
    | 'gpt-3.5-turbo-1106'
    | 'gpt-3.5-turbo-0125'
    | 'gpt-3.5-turbo-16k-0613'
    | null;

  /**
   * Whether to enable
   * [parallel function calling](https://platform.openai.com/docs/guides/function-calling/parallel-function-calling)
   * during tool use.
   */
  parallel_tool_calls?: boolean;

  /**
   * Specifies the format that the model must output. Compatible with
   * [GPT-4o](https://platform.openai.com/docs/models/gpt-4o),
   * [GPT-4 Turbo](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4),
   * and all GPT-3.5 Turbo models since `gpt-3.5-turbo-1106`.
   *
   * Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the
   * message the model generates is valid JSON.
   *
   * **Important:** when using JSON mode, you **must** also instruct the model to
   * produce JSON yourself via a system or user message. Without this, the model may
   * generate an unending stream of whitespace until the generation reaches the token
   * limit, resulting in a long-running and seemingly "stuck" request. Also note that
   * the message content may be partially cut off if `finish_reason="length"`, which
   * indicates the generation exceeded `max_tokens` or the conversation exceeded the
   * max context length.
   */
  response_format?: AssistantResponseFormatOption | null;

  /**
   * If `true`, returns a stream of events that happen during the Run as server-sent
   * events, terminating when the Run enters a terminal state with a `data: [DONE]`
   * message.
   */
  stream?: boolean | null;

  /**
   * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
   * make the output more random, while lower values like 0.2 will make it more
   * focused and deterministic.
   */
  temperature?: number | null;

  /**
   * If no thread is provided, an empty thread will be created.
   */
  thread?: ThreadCreateAndRunParams.Thread;

  /**
   * Controls which (if any) tool is called by the model. `none` means the model will
   * not call any tools and instead generates a message. `auto` is the default value
   * and means the model can pick between generating a message or calling one or more
   * tools. `required` means the model must call one or more tools before responding
   * to the user. Specifying a particular tool like `{"type": "file_search"}` or
   * `{"type": "function", "function": {"name": "my_function"}}` forces the model to
   * call that tool.
   */
  tool_choice?: AssistantToolChoiceOption | null;

  /**
   * A set of resources that are used by the assistant's tools. The resources are
   * specific to the type of tool. For example, the `code_interpreter` tool requires
   * a list of file IDs, while the `file_search` tool requires a list of vector store
   * IDs.
   */
  tool_resources?: ThreadCreateAndRunParams.ToolResources | null;

  /**
   * Override the tools the assistant can use for this run. This is useful for
   * modifying the behavior on a per-run basis.
   */
  tools?: Array<
    AssistantsAPI.CodeInterpreterTool | AssistantsAPI.FileSearchTool | AssistantsAPI.FunctionTool
  > | null;

  /**
   * An alternative to sampling with temperature, called nucleus sampling, where the
   * model considers the results of the tokens with top_p probability mass. So 0.1
   * means only the tokens comprising the top 10% probability mass are considered.
   *
   * We generally recommend altering this or temperature but not both.
   */
  top_p?: number | null;

  /**
   * Controls for how a thread will be truncated prior to the run. Use this to
   * control the intial context window of the run.
   */
  truncation_strategy?: ThreadCreateAndRunParams.TruncationStrategy | null;
}
```

The API expects a thread_id: https://platform.openai.com/docs/api-reference/runs/createRun

The function that does the call passes the body:
```
/**
   * Create a thread and run it in one request.
   */
  createAndRun(
    body: ThreadCreateAndRunParamsNonStreaming,
    options?: Core.RequestOptions,
  ): APIPromise<RunsAPI.Run>;
  createAndRun(
    body: ThreadCreateAndRunParamsStreaming,
    options?: Core.RequestOptions,
  ): APIPromise<Stream<AssistantsAPI.AssistantStreamEvent>>;
  createAndRun(
    body: ThreadCreateAndRunParamsBase,
    options?: Core.RequestOptions,
  ): APIPromise<Stream<AssistantsAPI.AssistantStreamEvent> | RunsAPI.Run>;
  createAndRun(
    body: ThreadCreateAndRunParams,
    options?: Core.RequestOptions,
  ): APIPromise<RunsAPI.Run> | APIPromise<Stream<AssistantsAPI.AssistantStreamEvent>> {
    return this._client.post('/threads/runs', {
      body,
      ...options,
      headers: { 'OpenAI-Beta': 'assistants=v2', ...options?.headers },
      stream: body.stream ?? false,
    }) as APIPromise<RunsAPI.Run> | APIPromise<Stream<AssistantsAPI.AssistantStreamEvent>>;
  }
```

The body has the key thread, but not the key thread_id. This is why this is failing. In my opinion, this is why it fails.

Does this help?

**Comment by SpuriousGer** [comment]
I've modified the Node package quickly to show the output before sending to the API:
```
createAndRunPoll, body {
  thread: {
    id: 'thread_MH8WGkDDdn7UCdjlD0ITkYka',
    object: 'thread',
    created_at: 1721294693,
    metadata: {},
    tool_resources: { file_search: [Object] }
  },
  assistant_id: 'asst_1hIDkwEgk0hz6ileuJlIjU2z'
}
createAndRun, body {
  thread: {
    id: 'thread_MH8WGkDDdn7UCdjlD0ITkYka',
    object: 'thread',
    created_at: 1721294693,
    metadata: {},
    tool_resources: { file_search: [Object] }
  },
  assistant_id: 'asst_1hIDkwEgk0hz6ileuJlIjU2z'
}
Failed to generate content from PDF document BadRequestError: 400 Unknown parameter: 'thread.id'.
    at Function.generate (C:\Users\Jonas\WebstormProjects\paperless-handling-api\node_modules\openai\src\error.ts:70:14)
    at OpenAI.makeStatusError (C:\Users\Jonas\WebstormProjects\paperless-handling-api\node_modules\openai\src\core.ts:397:21)
    at OpenAI.makeRequest (C:\Users\Jonas\WebstormProjects\paperless-handling-api\node_modules\openai\src\core.ts:460:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Threads.createAndRunPoll (C:\Users\Jonas\WebstormProjects\paperless-handling-api\node_modules\openai\src\resources\beta\threads\threads.ts:106:4)
    at getDataFromExpenseInvoicePdf (C:\Users\Jonas\WebstormProjects\paperless-handling-api\src\services\openai.service.ts:82:17)
    at analyzePdfDocumentByOpenAiGpt (C:\Users\Jonas\WebstormProjects\paperless-handling-api\src\controllers\paperless.controller.ts:56:10)
    at postConsumption (C:\Users\Jonas\WebstormProjects\paperless-handling-api\src\controllers\paperless.controller.ts:23:26) {
  status: 400,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8a516bdcace04d6d-FRA',
    connection: 'keep-alive',
    'content-length': '165',
    'content-type': 'application/json',
    date: 'Thu, 18 Jul 2024 09:24:54 GMT',
    'openai-organization': 'jp-abig-gmbh',
    'openai-processing-ms': '10',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=yDUeCp7jhEnKyAVk8Rfse6a0QPI7RZ4fDXqL4tCAFIw-1721294694-1.0.1.1-RsoMivgKBF8ki9KvQGhRf2iYEDPCOpIBWP8napCVL0bCuABAW9MBeu.KkZ5PMjf.APss69gjOuB9zkL9rAztsA; path=/; expires=Thu, 18-Jul-24 09:54:54 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=y1K3c9UlL9XbPScAGJAy7fRybPQjEB8qkcLgpyGLuf4-1721294694023-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_4d25f23637411b975d3d91bc3911ccde'
  },
  request_id: 'req_4d25f23637411b975d3d91bc3911ccde',
  error: {
    message: "Unknown parameter: 'thread.id'.",
    type: 'invalid_request_error',
    param: 'thread.id',
    code: 'unknown_parameter'
  },
  code: 'unknown_parameter',
  param: 'thread.id',
  type: 'invalid_request_error'
}

```

**Comment by SpuriousGer** [comment]
Ok, this isn't a bug, but I think a bit of an iffy spot with the types of the SDK.

I had this code to create a thread:
```
const thread = await openai.beta.threads.create({
      messages: [
        {
          role: "user",
          content: invoiceExpensePrompt(),
          attachments: [
            { file_id: uploadedFile.id, tools: [{ type: "file_search" }] },
          ],
        },
      ],
    });
```

As a matter of fact, passing this thread to the run does not create a type error, but it should in my opinion.

What does work is the following, i.e. passing the payload that would create a thread also as the thread:
```
const run = await openai.beta.threads.createAndRunPoll({
      thread: {
        messages: [
          {
            role: "user",
            content: invoiceExpensePrompt(),
            attachments: [
              { file_id: uploadedFile.id, tools: [{ type: "file_search" }] },
            ],
          },
        ],
      },
      assistant_id: usedAssistant.id,
    });
```
